In [2]:
import numpy as np
import pandas as pd

# Load the DataSet
df = pd.read_csv("C:/Users/Abdullah Umer/Desktop/Data Sentinel Internship/Task4/Shopping_Trends.csv")

# Quick Preview of Dataset
print("✅ Dataset Preview:")
print(df.head())
print("\n Columns:", df.columns.tolist())
print("\n Basic Info:")
print(df.info())

# 1. Average Purchase Amount by Gender
avg_purchase_gender = df.groupby("Gender")["Purchase Amount (USD)"].mean().reset_index()
print("\n✅ Average Purchase Amount by Gender:")
print(avg_purchase_gender)

# 2. Total Purchase Amount by Category
total_purchase_category = df.groupby("Category")["Purchase Amount (USD)"].sum().reset_index()
print("\n✅ Total Purchase Amount by Category:")
print(total_purchase_category)

# 3. Average Age by Location
avg_age_location = df.groupby("Location")["Age"].mean().reset_index()
print("\n✅ Average Age by Location:")
print(avg_age_location)

# 4. Customer Count by Subscription Status
customer_count_subscription = df.groupby("Subscription Status")["Customer ID"].count().reset_index()
customer_count_subscription.rename(columns={"Customer ID": "Customer Count"}, inplace=True)
print("\n✅ Customer Count by Subscription Status:")
print(customer_count_subscription)

# 5. Multiple Aggregations: Gender-wise Summary
gender_summary = df.groupby("Gender").agg(
    Avg_Age=("Age", "mean"),
    Total_Spend=("Purchase Amount (USD)", "sum"),
    Avg_Spend=("Purchase Amount (USD)", "mean"),
    Count=("Customer ID", "count")
).reset_index()

print("\n✅ Gender-wise Summary (Aggregated):")
print(gender_summary)

✅ Dataset Preview:
   Customer ID  Age Gender Item Purchased  Category  Purchase Amount (USD)  \
0            1   55   Male         Blouse  Clothing                     53
1            2   19   Male        Sweater  Clothing                     64
2            3   50   Male          Jeans  Clothing                     73
3            4   21   Male        Sandals  Footwear                     90
4            5   45   Male         Blouse  Clothing                     49

        Location Size      Color  Season  Review Rating Subscription Status  \
0       Kentucky    L       Gray  Winter            3.1                 Yes
1          Maine    L     Maroon  Winter            3.1                 Yes
2  Massachusetts    S     Maroon  Spring            3.1                 Yes
3   Rhode Island    M     Maroon  Spring            3.5                 Yes
4         Oregon    M  Turquoise  Spring            2.7                 Yes

  Payment Method  Shipping Type Discount Applied Promo Code Used  \
0    Credit Card        Express              Yes             Yes
1  Bank Transfer        Express              Yes             Yes
2           Cash  Free Shipping              Yes             Yes
3         PayPal   Next Day Air              Yes             Yes
4           Cash  Free Shipping              Yes             Yes

   Previous Purchases Preferred Payment Method Frequency of Purchases
0                  14                    Venmo            Fortnightly
1                   2                     Cash            Fortnightly
2                  23              Credit Card                 Weekly
3                  49                   PayPal                 Weekly
4                  31                   PayPal               Annually

 Columns: ['Customer ID', 'Age', 'Gender', 'Item Purchased', 'Category', 'Purchase Amount (USD)', 'Location', 'Size', 'Color', 'Season', 'Review Rating', 'Subscription Status', 'Payment Method', 'Shipping Type', 'Discount Applied', 'Promo Code Used', 'Previous Purchases', 'Preferred Payment Method', 'Frequency of Purchases']

 Basic Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3900 entries, 0 to 3899
Data columns (total 19 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Customer ID               3900 non-null   int64
 1   Age                       3900 non-null   int64
 2   Gender                    3900 non-null   object
 3   Item Purchased            3900 non-null   object
 4   Category                  3900 non-null   object
 5   Purchase Amount (USD)     3900 non-null   int64
 6   Location                  3900 non-null   object
 7   Size                      3900 non-null   object
 8   Color                     3900 non-null   object
 9   Season                    3900 non-null   object
 10  Review Rating             3900 non-null   float64
 11  Subscription Status       3900 non-null   object
 12  Payment Method            3900 non-null   object
 13  Shipping Type             3900 non-null   object
 14  Discount Applied          3900 non-null   object
 15  Promo Code Used           3900 non-null   object
 16  Previous Purchases        3900 non-null   int64
 17  Preferred Payment Method  3900 non-null   object
 18  Frequency of Purchases    3900 non-null   object
dtypes: float64(1), int64(4), object(14)
memory usage: 579.0+ KB
None

✅ Average Purchase Amount by Gender:
   Gender  Purchase Amount (USD)
0  Female              60.249199
1    Male              59.536199

✅ Total Purchase Amount by Category:
      Category  Purchase Amount (USD)
0  Accessories                  74200
1     Clothing                 104264
2     Footwear                  36093
3    Outerwear                  18524

✅ Average Age by Location:
          Location        Age
0          Alabama  44.314607
1           Alaska  43.000000
2          Arizona  45.276923
3         Arkansas  44.101266
4       California  42.663158
5         Colorado  44.146667
6      Connecticut  47.320513
7         Delaware  43.069767
8          Florida  42.323529
9          Georgia  43.772152
10          Hawaii  42.692308
11           Idaho  43.301075
12        Illinois  43.282609
13         Indiana  48.050633
14            Iowa  40.173913
15          Kansas  43.079365
16        Kentucky  42.265823
17       Louisiana  48.154762
18           Maine  41.935065
19        Maryland  46.895349
20   Massachusetts  45.208333
21        Michigan  42.095890
22       Minnesota  45.477273
23     Mississippi  43.262500
24        Missouri  45.740741
25         Montana  43.822917
26        Nebraska  42.666667
27          Nevada  43.609195
28   New Hampshire  44.323944
29      New Jersey  45.029851
30      New Mexico  44.024691
31        New York  43.931034
32  North Carolina  45.730769
33    North Dakota  43.771084
34            Ohio  46.532468
35        Oklahoma  43.880000
36          Oregon  43.554054
37    Pennsylvania  42.972973
38    Rhode Island  46.476190
39  South Carolina  47.500000
40    South Dakota  44.014286
41       Tennessee  44.051948
42           Texas  42.740260
43            Utah  43.309859
44         Vermont  42.600000
45        Virginia  41.610390
46      Washington  44.397260
47   West Virginia  42.543210
48       Wisconsin  45.973333
49         Wyoming  42.507042

✅ Customer Count by Subscription Status:
  Subscription Status  Customer Count
0                  No            2847
1                 Yes            1053

✅ Gender-wise Summary (Aggregated):
   Gender    Avg_Age  Total_Spend  Avg_Spend  Count
0  Female  44.007212        75191  60.249199   1248
1    Male  44.097285       157890  59.536199   2652